import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "Registration Success",
    description: "Generated by create next app",
};

export default function RegisterSuccessLayout({
   children,
}: {
    children: React.ReactNode
}) {
    return <section>{children}</section>
}